# Generated by Django 5.1.5 on 2025-02-05 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parcours",
            options={"verbose_name": "Parcours", "verbose_name_plural": "Parcours"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["position"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="reponse",
            options={"verbose_name": "Réponse", "verbose_name_plural": "Réponses"},
        ),
    ]
