# Generated by Django 5.2.2 on 2025-06-12 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="counterentry",
            unique_together={("name", "date", "key")},
        ),
    ]
