# Generated by Django 5.1.5 on 2025-02-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Operateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Sujet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
            ],
        ),
    ]
