# Generated by Django 5.1.5 on 2025-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonegeographique",
            name="type",
            field=models.CharField(
                choices=[
                    ("Région", "Région"),
                    ("Département", "Département"),
                    ("Collectivité d'outre-mer", "Collectivité d'outre-mer"),
                    ("Communauté de communes", "Communauté de communes"),
                    ("Collectivité sui generis", "Collectivité sui generis"),
                ]
            ),
        ),
    ]
