# Generated by Django 5.1.7 on 2025-03-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="effectif_max",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="effectif_min",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
