# Generated by Django 5.1.5 on 2025-02-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0002_sujet_themes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouvertureGeographique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
            ],
            options={
                "verbose_name": "Couverture géographique",
                "verbose_name_plural": "Couvertures géographiques",
            },
        ),
        migrations.CreateModel(
            name="ZoneGeographique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
                ("type", models.CharField()),
            ],
            options={
                "verbose_name": "Zone géographique",
                "verbose_name_plural": "Zones géographiques",
            },
        ),
        migrations.AlterModelOptions(
            name="nature",
            options={
                "verbose_name": "Nature d'aide",
                "verbose_name_plural": "Natures d'aide",
            },
        ),
        migrations.AlterModelOptions(
            name="operateur",
            options={"verbose_name": "Opérateur", "verbose_name_plural": "Opérateurs"},
        ),
        migrations.AlterModelOptions(
            name="sujet",
            options={"verbose_name": "Sujet", "verbose_name_plural": "Sujets"},
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={"verbose_name": "Thème", "verbose_name_plural": "Thèmes"},
        ),
        migrations.CreateModel(
            name="Aide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.PositiveBigIntegerField()),
                ("nom", models.CharField()),
                ("slug", models.SlugField()),
                ("promesse", models.CharField(blank=True)),
                ("description_courte", models.TextField(blank=True)),
                ("description_longue", models.TextField(blank=True)),
                ("montant", models.CharField(blank=True)),
                ("lien", models.URLField(blank=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "nature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aides.nature"
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.operateur",
                    ),
                ),
                (
                    "operateurs_secondaires",
                    models.ManyToManyField(
                        related_name="aides_secondaires", to="aides.operateur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aide",
                "verbose_name_plural": "Aides",
            },
        ),
    ]
