# Generated by Django 5.1.5 on 2025-02-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0003_couverturegeographique_zonegeographique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="couverture_geographique",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.couverturegeographique",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="zones_geographiques",
            field=models.ManyToManyField(to="aides.zonegeographique"),
        ),
    ]
