# Generated by Django 5.1.5 on 2025-02-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0004_aide_couverture_geographique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="date_debut",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="date_fin",
            field=models.DateField(null=True),
        ),
    ]
