# Generated by Django 5.1.5 on 2025-02-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0005_alter_aide_date_debut_alter_aide_date_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="nature",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.nature",
            ),
        ),
    ]
