# Generated by Django 5.1.5 on 2025-02-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0006_alter_aide_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="operateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.operateur",
            ),
        ),
    ]
