# Generated by Django 5.1.5 on 2025-02-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0007_alter_aide_operateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonegeographique",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.zonegeographique",
            ),
        ),
    ]
