# Generated by Django 5.1.5 on 2025-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0008_zonegeographique_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonegeographique",
            name="numero",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
