# Generated by Django 5.1.5 on 2025-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0009_zonegeographique_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
