# Generated by Django 5.1.5 on 2025-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0010_alter_aide_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="lien",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
