# Generated by Django 5.2.2 on 2025-06-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0017_aide_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides",
                to="aides.organisme",
            ),
        ),
    ]
