# Generated by Django 5.2.3 on 2025-07-08 14:21

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0031_filiere_published_organisme_courriel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="conditions",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="contact",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="description",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_age",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_cumulable",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="etapes",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="exemple_projet",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="montant",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="participation_agriculteur",
            field=prose.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="type_depense",
            field=prose.fields.RichTextField(blank=True),
        ),
    ]
