# Generated by Django 5.2.4 on 2025-07-09 13:49

import product.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0032_alter_aide_conditions_alter_aide_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="conditions",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="contact",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="description",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_age",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_cumulable",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="etapes",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="exemple_projet",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="montant",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="participation_agriculteur",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="type_depense",
            field=product.fields.VendoredTrixRichTextField(blank=True),
        ),
    ]
