# Generated by Django 5.2.6 on 2025-09-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0047_aide_cc_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.aide",
                verbose_name="Dérivée de",
            ),
        ),
    ]
