# Generated by Django 5.2.6 on 2025-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0048_aide_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("01. À trier", "01. À trier"),
                    ("02. En analyse", "02. En analyse"),
                    ("03. Retenue - à structurer", "03. Retenue - à structurer"),
                    ("04. À éditorialiser", "04. À éditorialiser"),
                    ("05. À valider", "05. À valider"),
                    ("06. À publier", "06. À publier"),
                    ("07. Publiée", "07. Publiée"),
                    ("08. À mettre à jour", "08. À mettre à jour"),
                    ("10. À décliner", "10. À décliner"),
                    ("98. Non retenue", "98. Non retenue"),
                    ("99. Archivée", "99. Archivée"),
                ],
                default="01. À trier",
                verbose_name="État",
            ),
        ),
    ]
