# Generated by Django 5.2.8 on 2025-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0053_aide_compute_priority_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="is_territoire_en_deploiement",
            field=models.BooleanField(
                default=False, verbose_name="Territoire en déploiement"
            ),
        ),
    ]
