# Generated by Django 5.2.8 on 2025-11-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0054_aide_is_territoire_en_deploiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="first_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Date de première publication"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False,
                null=True,
                verbose_name="Date de dernière mise à jour publiée",
            ),
        ),
    ]
