# Generated by Django 5.2.8 on 2025-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0055_aide_first_published_at_alter_aide_last_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="bureau_valideur",
            field=models.CharField(
                blank=True, default="", verbose_name="Bureau valideur"
            ),
        ),
    ]
