# Generated by Django 5.2.8 on 2025-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0056_aide_bureau_valideur"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="base_juridique",
            field=models.CharField(
                blank=True, default="", verbose_name="Base juridique"
            ),
        ),
    ]
