# Generated by Django 5.2.8 on 2025-11-27 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0058_alter_aide_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filiere",
            name="code_naf",
        ),
        migrations.AddField(
            model_name="filiere",
            name="codes_naf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                null=True,
                size=None,
                verbose_name="Codes NAF associés",
            ),
        ),
    ]
