# Generated by Django 5.2.8 on 2025-11-27 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0059_remove_filiere_code_naf_filiere_codes_naf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sousfiliere",
            name="filiere",
        ),
        migrations.DeleteModel(
            name="Production",
        ),
        migrations.DeleteModel(
            name="SousFiliere",
        ),
    ]
