# Generated by Django 5.2.10 on 2026-01-07 10:47

from django.db import migrations, models


def data_migration(apps, schema_editor):
    Aide = apps.get_model("aides", "Aide")
    GroupementProducteurs = apps.get_model("aides", "GroupementProducteurs")
    mapping = {
        "ASA": "ASA",
        "CUMA": "CUMA",
        "GIEE": "GIEE",
        "Organisations de producteurs": "Organisation de producteurs (OP)",
        "SICA": "Coopérative (SCA ou SICA)",
        "SCA": "Coopérative (SCA ou SICA)",
    }
    for aide in (
        Aide.objects.exclude(beneficiaires=None)
        .exclude(beneficiaires=[])
        .exclude(beneficiaires=["Agriculteurs"])
    ):
        aide.eligibilite_beneficiaires.set(
            GroupementProducteurs.objects.filter(
                nom__in=[mapping[b] for b in aide.beneficiaires if b != "Agriculteurs"]
            )
        )


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0060_remove_sousfiliere_filiere_delete_production_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="eligibilite_beneficiaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.groupementproducteurs",
                verbose_name="Bénéficiaires",
            ),
        ),
        migrations.RunPython(data_migration),
        migrations.RemoveField(
            model_name="aide",
            name="beneficiaires",
        ),
    ]
