# Generated by Django 5.2.10 on 2026-01-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0061_remove_aide_beneficiaires_and_more"),
    ]

    operations = [
        migrations.RenameModel("GroupementProducteurs", "Beneficiaires"),
        migrations.AlterModelOptions(
            name="beneficiaires",
            options={
                "ordering": ("nom",),
                "verbose_name": "Type de bénéficiaires",
                "verbose_name_plural": "Types de bénéficiaires",
            },
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_beneficiaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.beneficiaires",
                verbose_name="Bénéficiaires",
            ),
        ),
        migrations.AddField(
            "Beneficiaires",
            "is_groupement",
            field=models.BooleanField(
                default=True, verbose_name="Est un groupement de producteurs"
            ),
        ),
    ]
