# Generated by Django 5.2.10 on 2026-01-09 10:41

from django.db import migrations, models


def data_migration(apps, *args):
    Aide = apps.get_model("aides", "Aide")
    Aide.objects.filter(status__in=("41", "50")).update(is_published=True)
    Aide.objects.filter(status="50").update(status="40")


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0062_rename_groupementproducteurs_to_beneficiaires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publiée"),
        ),
        migrations.RunPython(data_migration),
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("00", "0. Backlog - À prioriser"),
                    ("10", "1. Priorisée - Scope à vérif"),
                    ("11", "1.1 Bloquée"),
                    ("20", "2. Ok scope - À éditer"),
                    ("30", "3. Ok édito - À valider"),
                    ("31", "3.1 En attente validation métier"),
                    ("40", "4. Validée"),
                    ("41", "4.1 Validée puis à décliner"),
                    ("99", "99. Archivée"),
                ],
                default="00",
                verbose_name="État",
            ),
        ),
    ]
