# Generated by Django 5.2.10 on 2026-01-08 16:16

import django.contrib.postgres.indexes
import django.contrib.postgres.operations as postgres_operations
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0062_rename_groupementproducteurs_to_beneficiaires_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        postgres_operations.BtreeGinExtension(),
        postgres_operations.UnaccentExtension(),
        migrations.RunSQL("""
            CREATE TEXT SEARCH CONFIGURATION french_unaccent ( COPY = french );
            ALTER TEXT SEARCH CONFIGURATION french_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, french_stem;
        """),
        migrations.AddField(
            model_name="aide",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "nom", config="french_unaccent", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "promesse", config="french_unaccent", weight="A"
                        ),
                        django.contrib.postgres.search.SearchConfig("french_unaccent"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="french_unaccent", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("french_unaccent"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="aide",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="aides_aide_full_text_gin"
            ),
        ),
    ]
