# Generated by Django 5.2.11 on 2026-02-11 11:32

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Aide = apps.get_model("aides", "Aide")
    to_update = []
    for row in Aide.objects.all():
        row.sneak_peek_token = uuid.uuid4()
        to_update.append(row)
    Aide.objects.bulk_update(to_update, fields=["sneak_peek_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0063_aide_is_published_alter_aide_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="sneak_peek_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name="aide",
            name="sneak_peek_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
