# Generated by Django 5.2.12 on 2026-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aides', '0064_aide_sneak_peek_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aide',
            name='base_juridique',
            field=models.TextField(blank=True, default='', verbose_name='Base juridique'),
        ),
    ]
