# Generated by Django 5.2.11 on 2026-02-16 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0064_aide_sneak_peek_token"),
        ("workflow", "0002_data_first_load"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="aide",
            name="cc_to",
        ),
    ]
