# Generated by Django 5.2.11 on 2026-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0065_aide_search_vector_aide_aides_aide_full_text_gin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisme",
            old_name="logo_filename",
            new_name="illustration_filename",
        ),
        migrations.RenameField(
            model_name="organisme",
            old_name="logo",
            new_name="illustration",
        ),
        migrations.AddField(
            model_name="sujet",
            name="illustration",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="sujet",
            name="illustration_filename",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="illustration",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="illustration_filename",
            field=models.CharField(blank=True),
        ),
    ]
