# Generated by Django 5.2.12 on 2026-03-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aides', '0065_alter_aide_base_juridique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aide',
            name='aap_ami',
        ),
        migrations.RemoveField(
            model_name='aide',
            name='duree_accompagnement',
        ),
        migrations.RemoveField(
            model_name='aide',
            name='eligibilite_age',
        ),
    ]
