# Generated by Django 5.2.11 on 2026-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0066_remove_aide_aap_ami_remove_aide_duree_accompagnement_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisme",
            old_name="logo_filename",
            new_name="illustration_filename",
        ),
        migrations.RenameField(
            model_name="organisme",
            old_name="logo",
            new_name="illustration",
        ),
        migrations.AddField(
            model_name="sujet",
            name="illustration",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="sujet",
            name="illustration_filename",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="illustration",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="illustration_filename",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="illustration",
            field=models.BinaryField(blank=True),
        ),
        migrations.RemoveField(
            model_name="organisme",
            name="illustration_filename",
        ),
        migrations.RemoveField(
            model_name="sujet",
            name="illustration_filename",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="illustration_filename",
        ),
        migrations.AddField(
            model_name="organisme",
            name="has_illustration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(illustration=b"", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="sujet",
            name="has_illustration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(illustration=b"", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="has_illustration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(illustration=b"", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
