# Generated by Django 5.2.13 on 2026-04-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0066_remove_aide_aap_ami_remove_aide_duree_accompagnement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseJuridique",
            options={
                "verbose_name": "Base juridique",
                "verbose_name_plural": "Bases juridiques",
            },
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(verbose_name="Libellé")),
                (
                    "url",
                    models.URLField(
                        verbose_name="Adresse",
                        help_text="Une URL valide, exemple https://legifrance.gouv.fr/",
                    ),
                ),
                (
                    "aide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bases_juridiques",
                        to="aides.aide",
                    ),
                ),
            ],
        ),
    ]
