# Generated by Django 5.2.11 on 2026-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0066_rename_logo_filename_organisme_illustration_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sujet",
            name="icon_name",
            field=models.CharField(
                blank=True, verbose_name="(technique) Nom de l’icône"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="icon_name",
            field=models.CharField(
                blank=True, verbose_name="(technique) Nom de l’icône"
            ),
        ),
    ]
