# Generated by Django 5.2.13 on 2026-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aides', '0067_basejuridique'),
    ]

    operations = [
        migrations.AddField(
            model_name='basejuridique',
            name='commentaire',
            field=models.CharField(blank=True, verbose_name='Commentaire'),
        ),
    ]
