# Generated by Django 5.2.11 on 2026-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0067_sujet_icon_name_theme_icon_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonegeographique",
            name="prefix",
            field=models.CharField(
                blank=True,
                help_text='Exemples\xa0: "Dans le", "En", etc.',
                verbose_name="Préfixe",
            ),
        ),
    ]
