# Generated by Django 5.2.11 on 2026-03-05 18:03

from django.db import migrations, models


def data_migration(apps, schema_editor):
    Type = apps.get_model("aides", "Type")
    types = [
        "Financement",
        "Prêt",
        "Avantage fiscal",
        "Assistance",
        "Conseil",
        "Étude",
        "Formation",
        "Informations",
    ]
    for i, type in enumerate(types):
        Type.objects.filter(nom=type).update(position=i + 1)


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0068_zonegeographique_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="position",
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(data_migration),
        migrations.AlterModelOptions(
            name="type",
            options={
                "ordering": ("position",),
                "verbose_name": "Type d'aides",
                "verbose_name_plural": "Types d'aides",
            },
        ),
    ]
