# Generated by Django 5.2.11 on 2026-03-06 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0069_type_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="type",
            options={
                "ordering": ("position",),
                "verbose_name": "Type d'aides",
                "verbose_name_plural": "Types d'aides",
            },
        ),
        migrations.RemoveField(
            model_name="organisme",
            name="illustration_filename",
        ),
        migrations.RemoveField(
            model_name="sujet",
            name="illustration_filename",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="illustration_filename",
        ),
    ]
