# Generated by Django 5.2.11 on 2026-03-12 13:29

from django.db import migrations, models


def data_migration(apps, schema_editor):
    from aides.models import Aide

    for couv in Aide.CouvertureGeographique:
        Aide.objects.filter(couverture_geographique=couv.label).update(
            couverture_geographique=couv.value
        )
        Aide.objects.filter(couverture_geographique__iexact="Outre mer").update(
            couverture_geographique=Aide.CouvertureGeographique.OUTRE_MER
        )


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0070_type_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="couverture_geographique",
            field=models.CharField(
                choices=[
                    ("01 National", "National"),
                    ("04 Régional", "Régional"),
                    ("02 France métropolitaine", "France métropolitaine"),
                    ("03 Outre-mer", "Outre-mer"),
                    ("05 Départemental", "Départemental"),
                    ("06 Local", "Local"),
                ],
                default="01 National",
                verbose_name="Couverture géographique",
            ),
        ),
        migrations.RunPython(data_migration, reverse_code=lambda x, y: None),
    ]
