# Generated by Django 5.2.11 on 2026-03-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0071_alter_aide_couverture_geographique"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisme",
            name="has_illustration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(illustration=b"", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="sujet",
            name="has_illustration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(illustration=b"", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="has_illustration",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(illustration=b"", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
