# Generated by Django 5.2.13 on 2026-04-20 14:55

from django.db import migrations, models


def data_populate_departements_position(apps, schema_editor):
    ZoneGeographique = apps.get_model("aides", "ZoneGeographique")
    for zone_geo in ZoneGeographique.objects.all():
        try:
            zone_geo.position = int(zone_geo.code)
        except ValueError:
            zone_geo.position = int(zone_geo.code[0]) * 10
        zone_geo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0073_alter_aide_couverture_geographique"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonegeographique",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="zonegeographique",
            name="prefixe_determinant",
            field=models.CharField(
                blank=True,
                help_text="Exemples\xa0: «\xa0les\xa0», «\xa0la\xa0», etc.",
                verbose_name="Déterminant",
            ),
        ),
        migrations.AddField(
            model_name="zonegeographique",
            name="prefixe_localisation",
            field=models.CharField(
                blank=True,
                help_text="Exemples\xa0: «\xa0dans la\xa0», «\xa0en\xa0», etc.",
                verbose_name="Préfixe en «\xa0dans\xa0»",
            ),
        ),
        migrations.RemoveField(
            model_name="zonegeographique",
            name="prefix",
        ),
        migrations.RunPython(
            data_populate_departements_position, reverse_code=lambda x, y: None
        ),
        migrations.AlterModelOptions(
            name="zonegeographique",
            options={
                "ordering": ("type", "position", "code"),
                "verbose_name": "Zone géographique",
                "verbose_name_plural": "Zones géographiques",
            },
        ),
    ]
