# Generated by Django 5.2.14 on 2026-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aides', '0074_alter_zonegeographique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisme',
            name='sous_famille',
            field=models.CharField(blank=True, choices=[('Région', 'Région'), ('Département', 'Département'), ('Opérateur', 'Opérateur'), ('MAASA / DRAAF / DDT', 'MAASA / DRAAF / DDT'), ('MTE / DREAL', 'MTE / DREAL'), ('Affaires sociales / DREETS / DEETS', 'Affaires sociales / DREETS / DEETS'), ('Travail / DREETS / DEETS', 'Travail / DREETS / DEETS'), ('Finances', 'Finances'), ('Agences de l’eau', 'Agences de l’eau'), ('Autres', 'Autres')], verbose_name='Sous-famille'),
        ),
    ]
