# Generated by Django 5.2.13 on 2026-04-14 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0074_alter_zonegeographique_options_and_more"),
        ("workflow", "0002_data_first_load"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="aide",
            name="cc_to",
        ),
    ]
