# Generated by Django 5.2.15 on 2026-06-15 12:47

from collections import defaultdict

from django.db import migrations, models


def data_migration(apps, schema_editor):
    bases = defaultdict(set)
    to_delete = set()
    Aide = apps.get_model("aides", "Aide")
    BaseJuridique = apps.get_model("aides", "BaseJuridique")
    for base in BaseJuridique.objects.all():
        if base.url in bases:
            to_delete.add(base.pk)
        bases[base.url].add((base.pk, base.aide_id))
    for relations in bases.values():
        for relation in relations:
            Aide.base_juridique.through.objects.create(
                basejuridique_id=relation[0], aide_id=relation[1]
            )
    BaseJuridique.objects.filter(pk__in=to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0075_organisme_sous_famille"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="base_juridique",
        ),
        migrations.AddField(
            model_name="aide",
            name="base_juridique",
            field=models.ManyToManyField(
                blank=True, to="aides.basejuridique", verbose_name="Bases juridiques"
            ),
        ),
        migrations.RunPython(data_migration, reverse_code=None),
        migrations.AlterField(
            model_name="basejuridique",
            name="url",
            field=models.URLField(
                help_text="Une URL valide, exemple https://legifrance.gouv.fr/",
                unique=True,
                verbose_name="Adresse",
            ),
        ),
        migrations.RemoveField(
            model_name="basejuridique",
            name="aide",
        ),
    ]
