# Generated by Django 5.2.17 on 2026-08-11 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0076_remove_basejuridique_aide_remove_aide_base_juridique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides",
                to="aides.organisme",
                verbose_name="Organisme porteur",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="organisme_instructeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides_instruites",
                to="aides.organisme",
                verbose_name="Organisme instructeur",
            ),
        ),
    ]
