# Generated by Django 5.2.17 on 2026-08-11 13:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0077_aide_organisme_instructeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisme",
            name="adresse",
            field=models.TextField(blank=True, verbose_name="Adresse physique"),
        ),
        migrations.AddField(
            model_name="organisme",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                help_text="Au format français (01 23 45 67 89), ou sans les espaces (0123456789), ou avec des points (01.23.45.67.89), ou avec des slashs (01/23/45/67/89), ou au format international (+33 1 23 45 67 89), ou sans espaces (+33123456789)...",
                verbose_name="Numéro de téléphone",
            ),
        ),
    ]
