# Generated by Django 5.2.17 on 2026-08-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0078_organisme_adresse_organisme_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisme",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="aides.organisme",
                verbose_name="Organisme parent",
            ),
        ),
    ]
