# Generated by Django 5.2.17 on 2026-08-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0079_organisme_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisme",
            name="horaires",
            field=models.TextField(blank=True, verbose_name="Horaires"),
        ),
        migrations.AddField(
            model_name="organisme",
            name="siren",
            field=models.CharField(blank=True, verbose_name="Numéro SIREN"),
        ),
        migrations.AddField(
            model_name="organisme",
            name="id_annuaire_service_public",
            field=models.CharField(blank=True, editable=False),
        ),
    ]
