# Generated by Django 5.2.17 on 2026-09-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0080_organisme_horaires_organisme_siren"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificiteLocale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specificites",
                    models.TextField(verbose_name="Spécificités", blank=True),
                ),
                (
                    "aide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.aide",
                        related_name="specificites_locales",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.organisme",
                        related_name="specificites_locales_des_aides",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spécificité locale",
                "verbose_name_plural": "Spécificités locales",
            },
        ),
    ]
