[project]
requires-python = ">=3.11"
name = "aides-agri"
version = "0.1.0"
dependencies = [
  "django ~=5.1",
  "psycopg[binary] ~=3.0",
]

[dependency-groups]
dev = [
  "djade",
  "django-browser-reload",
  "django-debug-toolbar",
  "ruff",
]
