# Generated by Django 5.2.15 on 2026-07-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPageQuote",
            options={
                "verbose_name": "Citation pour la page À propos",
                "verbose_name_plural": "Citations pour la page À propos",
            },
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(verbose_name="Verbatim")),
                ("author", models.CharField(verbose_name="Auteur ou autrice")),
                (
                    "source_label",
                    models.CharField(blank=True, verbose_name="Source\xa0: libellé"),
                ),
                (
                    "source_url",
                    models.CharField(blank=True, verbose_name="Source\xa0: lien"),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="aboutpagequote",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Citation pour la page À propos",
                "verbose_name_plural": "Citations pour la page À propos",
            },
        ),
        migrations.AddField(
            model_name="aboutpagequote",
            name="ordering",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="ordering"
            ),
        ),
    ]
