# Generated by Django 5.2.17 on 2026-08-14 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aides", "0076_remove_basejuridique_aide_remove_aide_base_juridique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("token", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        limit_choices_to={"type": "03 Département"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.zonegeographique",
                    ),
                ),
                ("filieres", models.ManyToManyField(blank=True, to="aides.filiere")),
                ("sujets", models.ManyToManyField(blank=True, to="aides.sujet")),
                ("themes", models.ManyToManyField(blank=True, to="aides.theme")),
            ],
        ),
    ]
