# Generated by Django 5.1.7 on 2025-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiere",
            name="position",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
