# Generated by Django 5.1.7 on 2025-03-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0002_alter_filiere_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="production",
            name="sous_filiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agri.sousfiliere",
            ),
        ),
        migrations.AlterField(
            model_name="sousfiliere",
            name="filiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agri.filiere",
            ),
        ),
    ]
