# Generated by Django 5.1.7 on 2025-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0003_alter_production_sous_filiere_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupementProducteurs",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                ("libelle", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Groupement de producteurs",
                "verbose_name_plural": "Groupement de producteurs",
            },
        ),
    ]
