# Generated by Django 5.2.15 on 2026-06-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aides", "0076_remove_basejuridique_aide_remove_aide_base_juridique_and_more"),
        ("referentiel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1_NEW", "1. Nouvelle"),
                            ("1_1_UPDATED", "1.1. Mise à jour"),
                            ("2_IN_PROGRESS", "2. En traitement"),
                            ("3_DONE", "3. Traitée"),
                        ],
                        default="1_NEW",
                        verbose_name="État",
                    ),
                ),
                (
                    "aide",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="aides.aide",
                        verbose_name="Aide dans Aides Agri",
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="referentiel.demarche",
                        verbose_name="Démarche dans le référentiel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawDataSchemaDispositifAide",
            fields=[
                (
                    "rawdata_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="integration.rawdata",
                    ),
                ),
                ("source", models.CharField()),
                (
                    "id_externe",
                    models.CharField(
                        verbose_name="Identifiant dans le système d‘information source"
                    ),
                ),
                ("titre", models.CharField(verbose_name="Titre")),
                ("promesse", models.CharField(blank=True, verbose_name="Promesse")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "eligibilite",
                    models.TextField(
                        blank=True, verbose_name="Conditions d’éligibilité"
                    ),
                ),
                (
                    "types_aides",
                    models.CharField(blank=True, verbose_name="Types d’aides"),
                ),
                (
                    "porteurs",
                    models.JSONField(blank=True, null=True, verbose_name="Porteurs"),
                ),
                (
                    "programmes_parents",
                    models.CharField(blank=True, verbose_name="Programmes parents"),
                ),
                (
                    "referents_internes",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Référents internes"
                    ),
                ),
                ("url_source", models.URLField(blank=True, verbose_name="URL source")),
                ("cibles", models.CharField(blank=True, verbose_name="Bénéficiaires")),
                (
                    "eligibilite_geographique",
                    models.CharField(
                        blank=True, verbose_name="Couverture géographique de l’aide"
                    ),
                ),
                (
                    "eligibilite_geographique_exclusions",
                    models.CharField(
                        blank=True,
                        verbose_name="Couverture géographique de l’aide ‑ exclusions",
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d’ouverture"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                (
                    "date_mise_a_jour",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "base_juridique",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Bases juridiques"
                    ),
                ),
                (
                    "ciblage_secteur_activite",
                    models.CharField(
                        blank=True, verbose_name="Secteurs d’activité concernés"
                    ),
                ),
                (
                    "ciblage_naf",
                    models.CharField(blank=True, verbose_name="Ciblage – codes NAF"),
                ),
                (
                    "ciblage_naf_exclusions",
                    models.CharField(
                        blank=True, verbose_name="Ciblage – codes NAF – exclusions"
                    ),
                ),
                (
                    "eligibilite_effectif_minimal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Effectif minimal",
                    ),
                ),
                (
                    "eligibilite_effectif_maximal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Effectif maximal",
                    ),
                ),
                (
                    "eligibilite_annees_existence_minimal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Nombre d’années d’existence minimal",
                    ),
                ),
                (
                    "eligibilite_forme_juridique",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Forme juridique",
                    ),
                ),
                (
                    "eligibilite_forme_juridique_exclusions",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Forme juridique – exclusions",
                    ),
                ),
                (
                    "eligibilite_categorie_taille_entreprise",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Catégories de tailles d’entreprises",
                    ),
                ),
                (
                    "chainage_paiement",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Identifiant de la démarche dont cette démarche-ci est la demande de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée brute au schéma interministériel des aides",
                "verbose_name_plural": "Donnée brutes au schéma interministériel des aides",
                "unique_together": {("source", "id_externe")},
            },
            bases=("integration.rawdata", models.Model),
        ),
    ]
