# Generated by Django 5.2.11 on 2026-02-06 13:51

import django.db.models.deletion
import django.db.models.functions.text
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemarcheAgricole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(unique=True)),
                ("titre", models.CharField()),
                ("promesse", models.CharField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("eligibilite", models.TextField(blank=True)),
                ("url_source", models.URLField(blank=True)),
                ("date_ouverture", models.DateField(blank=True, null=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
                ("date_mise_a_jour", models.DateField(auto_now=True)),
                (
                    "types_aides",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "ASSISTANCE"),
                            (2, "AVANTAGE_FISCAL"),
                            (4, "CONSEIL"),
                            (8, "ETUDE"),
                            (16, "FINANCEMENT"),
                            (32, "FORMATION"),
                            (64, "INFORMATION"),
                            (128, "PRET"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "cibles",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "PROFESSIONNELS"),
                            (2, "PARTICULIERS"),
                            (4, "ASSOCIATIONS"),
                            (8, "SECTEUR_PUBLIC"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField()),
                ("siren", models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Porteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roles",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "DIFFUSEUR"),
                            (2, "FINANCEUR"),
                            (4, "INSTRUCTEUR"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.demarcheagricole",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.organisme",
                    ),
                ),
            ],
            options={
                "unique_together": {("demarche", "organisme")},
            },
        ),
        migrations.AddField(
            model_name="demarcheagricole",
            name="porteurs_aides",
            field=models.ManyToManyField(
                blank=True, through="referentiel.Porteur", to="referentiel.organisme"
            ),
        ),
        migrations.AddField(
            model_name="demarcheagricole",
            name="programmes_parents",
            field=models.ManyToManyField(blank=True, to="referentiel.programme"),
        ),
        migrations.CreateModel(
            name="Territoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("REG", "Région"),
                            ("DEP", "Département"),
                            ("COM_COMER", "Collectivité d'outre-mer"),
                            ("EPCI", "Intercommunalité"),
                            ("COM", "Commune"),
                        ],
                        max_length=9,
                    ),
                ),
                ("code", models.CharField()),
                (
                    "code_cog",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "type", models.Value("-"), "code"
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("nom", models.CharField()),
                (
                    "intercommunalite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="referentiel.territoire",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="referentiel.territoire",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="demarcheagricole",
            name="eligibilite_geographique",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches_eligibilite",
                to="referentiel.territoire",
            ),
        ),
        migrations.AddField(
            model_name="demarcheagricole",
            name="eligibilite_geographique_exclusions",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches_eligibilite_exclusion",
                to="referentiel.territoire",
            ),
        ),
        migrations.AddConstraint(
            model_name="territoire",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["REG", "DEP", "COM_COMER", "EPCI", "COM"])
                ),
                name="referentiel_Territoire_type_Type",
            ),
        ),
    ]
