# Generated by Django 5.2.13 on 2026-04-14 11:37

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField()),
                ("siren", models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Demarche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1. Nouvelle", "New"),
                            ("1.1 Mise à jour", "Updated"),
                            ("3. Traitée", "Done"),
                        ],
                        default="1. Nouvelle",
                    ),
                ),
                ("date_updated", models.DateField(auto_now=True)),
                ("titre", models.CharField()),
                ("promesse", models.CharField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("eligibilite", models.TextField(blank=True)),
                ("url_source", models.URLField(blank=True)),
                ("date_ouverture", models.DateField(blank=True, null=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
                (
                    "types_aides",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "ASSISTANCE"),
                            (2, "AVANTAGE_FISCAL"),
                            (4, "CONSEIL"),
                            (8, "ETUDE"),
                            (16, "FINANCEMENT"),
                            (32, "FORMATION"),
                            (64, "INFORMATION"),
                            (128, "PRET"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "cibles",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "PROFESSIONNELS"),
                            (2, "PARTICULIERS"),
                            (4, "ASSOCIATIONS"),
                            (8, "SECTEUR_PUBLIC"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "secteurs_concernes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "ciblage_nafs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "ciblage_nafs_exclusions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "bases_juridiques",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "eligibilite_effectifs_minimaux",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "eligibilite_effectifs_maximaux",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "eligibilite_categorie_entreprise",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(1, "MIC"), (2, "PME"), (4, "ETI"), (8, "GE")],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "eligibilite_age_minimal",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "eligibilite_formes_juridiques",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "eligibilite_formes_juridiques_exclusions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "demande_de_paiement_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.demarche",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Porteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roles",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "DIFFUSEUR"),
                            (2, "FINANCEUR"),
                            (4, "INSTRUCTEUR"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.demarche",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.organisme",
                    ),
                ),
            ],
            options={
                "unique_together": {("demarche", "organisme")},
            },
        ),
        migrations.AddField(
            model_name="demarche",
            name="porteurs_aides",
            field=models.ManyToManyField(
                blank=True, through="referentiel.Porteur", to="referentiel.organisme"
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="programmes_parents",
            field=models.ManyToManyField(blank=True, to="referentiel.programme"),
        ),
        migrations.CreateModel(
            name="Territoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("REG", "Région"),
                            ("DEP", "Département"),
                            ("COM_COMER", "Collectivité d'outre-mer"),
                            ("EPCI", "Intercommunalité"),
                            ("COM", "Commune"),
                        ],
                        max_length=9,
                    ),
                ),
                ("code", models.CharField()),
                (
                    "code_cog",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "type", models.Value("-"), "code"
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("nom", models.CharField()),
                (
                    "intercommunalite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="referentiel.territoire",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="referentiel.territoire",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="demarche",
            name="eligibilite_geographique",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches_eligibilite",
                to="referentiel.territoire",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="eligibilite_geographique_exclusions",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches_eligibilite_exclusion",
                to="referentiel.territoire",
            ),
        ),
        migrations.AddConstraint(
            model_name="territoire",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["REG", "DEP", "COM_COMER", "EPCI", "COM"])
                ),
                name="referentiel_Territoire_type_Type",
            ),
        ),
    ]
