# Generated by Django 5.2.14 on 2026-05-19 08:54

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(verbose_name="Nom")),
                ("siren", models.CharField(blank=True, verbose_name="Numéro Siren")),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(verbose_name="Nom")),
            ],
        ),
        migrations.CreateModel(
            name="Demarche",
            options={"verbose_name": "Démarche", "verbose_name_plural": "Démarches"},
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(unique=True, verbose_name="Identifiant")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1_NEW", "1. Nouvelle"),
                            ("1_1_UPDATED", "1.1. Mise à jour"),
                            ("2_IN_PROGRESS", "2. En traitement"),
                            ("3_DONE", "3. Traitée"),
                        ],
                        default="1_NEW",
                        verbose_name="État",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("titre", models.CharField(verbose_name="Titre")),
                (
                    "promesse",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Promesse"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Description"
                    ),
                ),
                (
                    "eligibilite",
                    models.TextField(blank=True, verbose_name="Critères d’éligibilité"),
                ),
                ("url_source", models.URLField(blank=True, verbose_name="URL source")),
                (
                    "date_ouverture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d’ouverture"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                (
                    "ciblage_naf",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Ciblage – Codes NAF",
                    ),
                ),
                (
                    "ciblage_naf_exclusions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Ciblage – Codes NAF – exclusions",
                    ),
                ),
                (
                    "ciblage_secteur_activite",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Ciblage – Secteurs d’activité concernés",
                    ),
                ),
                (
                    "eligibilite_effectif_minimal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Effectif minimal",
                    ),
                ),
                (
                    "eligibilite_effectif_maximal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Effectif maximal",
                    ),
                ),
                (
                    "eligibilite_annees_existence_minimal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Éligibilité – Nombre d’années d’existence minimal",
                    ),
                ),
                (
                    "eligibilite_forme_juridique",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Éligibilité – Forme juridique",
                    ),
                ),
                (
                    "eligibilite_forme_juridique_exclusions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Éligibilité – Forme juridique – Exclusions",
                    ),
                ),
                (
                    "types_aides",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "ASSISTANCE"),
                            (2, "AVANTAGE_FISCAL"),
                            (4, "CONSEIL"),
                            (8, "ETUDE"),
                            (16, "FINANCEMENT"),
                            (32, "FORMATION"),
                            (64, "INFORMATION"),
                            (128, "PRET"),
                        ],
                        default=0,
                        null=True,
                        verbose_name="Types d’aides",
                    ),
                ),
                (
                    "cibles",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "PROFESSIONNELS"),
                            (2, "PARTICULIERS"),
                            (4, "ASSOCIATIONS"),
                            (8, "SECTEUR_PUBLIC"),
                        ],
                        default=0,
                        null=True,
                        verbose_name="Bénéficiaires",
                    ),
                ),
                (
                    "eligibilite_categorie_taille_entreprise",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[(1, "MIC"), (2, "PME"), (4, "ETI"), (8, "GE")],
                        default=0,
                        null=True,
                        verbose_name="Éligibilité – Catégories de tailles d’entreprises",
                        help_text="N’utiliser que si l’éligibilité repose sur une combinaison de critères et ne se limite pas au nombre de salariés.",
                    ),
                ),
                (
                    "demande_de_paiement_de",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demande_de_paiement",
                        to="referentiel.demarche",
                        verbose_name="Identifiant de la démarche dont cette démarche-ci est la demande de paiement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseJuridique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(verbose_name="Libellé")),
                (
                    "url",
                    models.URLField(
                        help_text="Une URL valide, exemple https://legifrance.gouv.fr/",
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bases_juridiques",
                        to="referentiel.demarche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base juridique",
                "verbose_name_plural": "Bases juridiques",
            },
        ),
        migrations.CreateModel(
            name="Porteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roles",
                    django_enum.fields.SmallIntegerFlagField(
                        blank=True,
                        choices=[
                            (1, "DIFFUSEUR"),
                            (2, "FINANCEUR"),
                            (4, "INSTRUCTEUR"),
                        ],
                        default=0,
                        null=True,
                        verbose_name="Rôles",
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.demarche",
                    ),
                ),
                (
                    "organisme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.organisme",
                    ),
                ),
            ],
            options={
                "unique_together": {("demarche", "organisme")},
            },
        ),
        migrations.CreateModel(
            name="ReferentInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, verbose_name="Nom complet")),
                (
                    "email",
                    models.CharField(blank=True, verbose_name="Adresse courriel"),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, verbose_name="Numéro de téléphone"),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referents_internes",
                        to="referentiel.demarche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Référent interne",
                "verbose_name_plural": "Référents internes",
            },
        ),
        migrations.AddField(
            model_name="demarche",
            name="porteurs",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches",
                through="referentiel.Porteur",
                to="referentiel.organisme",
                verbose_name="Porteurs",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="programmes_parents",
            field=models.ManyToManyField(
                blank=True,
                to="referentiel.programme",
                verbose_name="Programmes parents",
            ),
        ),
        migrations.CreateModel(
            name="Territoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("REG", "Région"),
                            ("DEP", "Département"),
                            ("COM_COMER", "Collectivité d'outre-mer"),
                            ("EPCI", "Intercommunalité"),
                            ("COM", "Commune"),
                        ],
                        max_length=9,
                        verbose_name="Type",
                    ),
                ),
                ("code", models.CharField(verbose_name="Code")),
                (
                    "code_cog",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "type", models.Value("-"), "code"
                        ),
                        output_field=models.CharField(),
                    ),
                ),
                ("nom", models.CharField(verbose_name="Nom")),
                (
                    "intercommunalite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="referentiel.territoire",
                        verbose_name="Intercommunalité",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="referentiel.territoire",
                        verbose_name="Territoire parent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="demarche",
            name="eligibilite_geographique",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches_eligibilite",
                to="referentiel.territoire",
                verbose_name="Couverture géographique de l’aide",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="eligibilite_geographique_exclusions",
            field=models.ManyToManyField(
                blank=True,
                related_name="demarches_eligibilite_exclusion",
                to="referentiel.territoire",
                verbose_name="Couverture géographique de l’aide - exclusions",
            ),
        ),
        migrations.AddConstraint(
            model_name="territoire",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type__in", ["REG", "DEP", "COM_COMER", "EPCI", "COM"])
                ),
                name="referentiel_Territoire_type_Type",
            ),
        ),
    ]
