# Generated by Django 5.2.13 on 2026-04-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True)),
                ('email', models.CharField(blank=True)),
                ('telephone', models.CharField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='demarche',
            name='demande_de_paiement_de',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande_de_paiement', to='referentiel.demarche'),
        ),
        migrations.AlterField(
            model_name='demarche',
            name='porteurs_aides',
            field=models.ManyToManyField(blank=True, related_name='demarches', through='referentiel.Porteur', to='referentiel.organisme'),
        ),
        migrations.AddField(
            model_name='demarche',
            name='referents_internes',
            field=models.ManyToManyField(related_name='demarches', to='referentiel.contact'),
        ),
    ]
