# Generated by Django 5.2.14 on 2026-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demarche',
            name='document_source',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Document source'),
        ),
    ]
