# Generated by Django 5.2.11 on 2026-02-16 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aides", "0064_aide_sneak_peek_token"),
        ("referentiel", "0001_initial"),
        ("referentiel_integration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.aide",
                        null=True,
                    ),
                ),
                (
                    "demarche_agricole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.demarcheagricole",
                        null=True,
                    ),
                ),
                (
                    "raw_demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel_integration.rawdemarche",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.aide",
                        null=True,
                    ),
                ),
                (
                    "demarche_agricole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel.demarcheagricole",
                        null=True,
                    ),
                ),
                (
                    "raw_demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="referentiel_integration.rawdemarche",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("user", "raw_demarche", "demarche_agricole", "aide")
                },
            },
        ),
    ]
