# Generated by Django 5.2.11 on 2026-02-16 15:41

from django.db import migrations


def data_migration(apps, schema_editor):
    Aide = apps.get_model("aides", "Aide")
    Assignment = apps.get_model("workflow", "Assignment")
    to_create = []
    for aide in Aide.objects.filter(assigned_to__isnull=False):
        to_create.append(Assignment(aide=aide, user_id=aide.assigned_to_id))
    Assignment.objects.bulk_create(to_create)
    CC = apps.get_model("workflow", "CC")
    to_create = []
    for aide in Aide.objects.cc_to.through.all():
        to_create.append(CC(aide=aide, user_id=aide.assigned_to_id))
    CC.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(data_migration, reverse_code=lambda x, y: None),
    ]
