# Generated by Django 5.2.13 on 2026-04-14 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDemarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1. Nouvelle', 'New'), ('1.1 Mise à jour', 'Updated'), ('2. En traitement', 'In Progress'), ('3. Traitée', 'Done')], default='1. Nouvelle')),
                ('demarche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.demarche')),
            ],
        ),
        migrations.CreateModel(
            name='RawDemarcheSchemaDispositifAide',
            fields=[
                ('rawdemarche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referentiel_integration.rawdemarche')),
                ('source', models.CharField()),
                ('id_externe', models.CharField()),
                ('titre', models.CharField()),
                ('promesse', models.CharField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('eligibilite', models.TextField(blank=True)),
                ('types_aides', models.CharField(blank=True)),
                ('porteurs', models.JSONField(blank=True, null=True)),
                ('programmes_parents', models.CharField(blank=True)),
                ('url_source', models.URLField(blank=True)),
                ('cibles', models.CharField(blank=True)),
                ('eligibilite_geographique', models.CharField(blank=True)),
                ('eligibilite_geographique_exclusions', models.CharField(blank=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Démarche brute au schéma interministériel des aides',
                'verbose_name_plural': 'Démarches brutes au schéma interministériel des aides',
                'unique_together': {('source', 'id_externe')},
            },
            bases=('referentiel_integration.rawdemarche', models.Model),
        ),
    ]
