# Generated by Django 5.2.11 on 2026-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DispositifSchemaAide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField()),
                ("id_externe", models.CharField()),
                ("titre", models.CharField()),
                ("promesse", models.CharField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("eligibilite", models.TextField(blank=True)),
                ("types_aides", models.CharField(blank=True)),
                ("porteurs", models.JSONField(blank=True, null=True)),
                ("programmes_parents", models.CharField(blank=True)),
                ("url_source", models.URLField(blank=True)),
                ("cibles", models.CharField(blank=True)),
                ("eligibilite_geographique", models.CharField(blank=True)),
                ("eligibilite_geographique_exclusions", models.CharField(blank=True)),
                ("date_ouverture", models.DateField(blank=True, null=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
                ("date_mise_a_jour", models.DateField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("source", "id_externe")},
            },
        ),
    ]
