# Generated by Django 5.2.13 on 2026-04-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referentiel_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="secteurs_concernes",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="bases_juridiques",
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="ciblage_nafs",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="ciblage_nafs_exclusions",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="demande_de_paiement_de",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="eligibilite_age_minimal",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="eligibilite_categorie_entreprise",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="eligibilite_effectifs_maximaux",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="eligibilite_effectifs_minimaux",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="eligibilite_formes_juridiques",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="eligibilite_formes_juridiques_exclusions",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rawdemarcheschemadispositifaide",
            name="referents_internes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
