# Generated by Django 5.1.4 on 2025-01-20 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pitch', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('external_url', models.URLField()),
                ('topics', models.ManyToManyField(related_name='incentives', to='questionnaire.topic')),
                ('incentive_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='catalog.incentivetype')),
            ],
        ),
        migrations.CreateModel(
            name='IncentiveSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('step', models.IntegerField()),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='catalog.incentive')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('further_description', models.TextField()),
                ('linked_projects', models.ManyToManyField(blank=True, related_name='related_to', to='catalog.project')),
                ('topics', models.ManyToManyField(related_name='projects', to='questionnaire.topic')),
            ],
        ),
        migrations.AddField(
            model_name='incentive',
            name='projects',
            field=models.ManyToManyField(related_name='incentives', to='catalog.project'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='primary_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_operator', to='catalog.publicbody'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='secondary_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_operator', to='catalog.publicbody'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.region'),
        ),
    ]
