# Generated by Django 5.2.15 on 2026-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides_feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackonaides",
            name="has_aide",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(aide_id=None, then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
                verbose_name="Concerne une aide",
            ),
        ),
    ]
